name = "ColorPalette"
uuid = "8ef84934-42ee-40db-9212-07205b84565a"
authors = ["Christian Kral <dr.christian.kral@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "^1.0.0"
